FROM node:alpine

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_ACCESS_REGION

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_DEFAULT_REGION=${AWS_ACCESS_REGION}

RUN apk update && apk upgrade && apk add nano git openssh-client


RUN apk --no-cache add python3 py3-pip

RUN  pip3 install --upgrade pip \
  && pip3 install --no-cache-dir awscli

# Downloading necessary configuration files
RUN aws s3 cp s3://stralom-deploys/financial/ssh/financial_web_deploy /root/.ssh/financial_deploy
RUN aws s3 cp s3://stralom-deploys/financial/ssh/financial_core_deploy /root/.ssh/financial_core_deploy
RUN aws s3 cp s3://stralom-deploys/financial/ssh/config /root/.ssh/config
#
## Set up SSH key for private repository access
# TODO: Refatorar para obter de forma dinamica das variaveis de ambiente
ENV NEXT_PUBLIC_ENDPOINT="https://api-financial.stralom.com/api/financial/"
ENV NEXT_PUBLIC_AUTH_ENDPOINT="https://api-authentication.stralom.com/"
ENV NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY="AIzaSyAP5Z6VXUoK9NHbwb6P97ZjxKKNUsBs0_E"
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="stralomauthentication.firebaseapp.com"
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID="stralomauthentication"
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="stralomauthentication.appspot.com"
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="83178434542"
ENV NEXT_PUBLIC_FIREBASE_APP_ID="1:83178434542:web:cb98f5066c3184f51aa8ff"
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-D0H8WTWXLC"

ENV GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan github.com >> /root/.ssh/known_hosts && \
    chmod 0400 /root/.ssh/financial_deploy /root/.ssh/financial_core_deploy && \
    eval "$(ssh-agent -s)" && \
    ssh-add /root/.ssh/financial_deploy  && \
    ssh-add /root/.ssh/financial_core_deploy


WORKDIR /app

#Clone the private repository with submodules
RUN git clone git@github.com:bStrano/stralom-financial-web.git .

RUN sed -i 's/git@github\.com:bStrano\/Stralom-Financial-Core\.git/ssh:\/\/github\.com-stralom-core\/bStrano\/Stralom-Financial-Core\.git/g' .gitmodules
#
RUN  git submodule update --init --recursive
RUN cd libs/stralom-financial-core && git checkout master && git pull

COPY package.json /app
RUN yarn install

RUN yarn build
EXPOSE 3000

CMD ["yarn","start"]

