name: Build and publish Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile-Prod
        push: true
        tags: blstrano/stralom-financial-api:latest
        build-args: |
          SSH_MAIN_PRIVATE_KEY=${{ secrets.SSH_MAIN_PRIVATE_KEY }}
          SSH_CORE_PRIVATE_KEY=${{ secrets.SSH_CORE_PRIVATE_KEY }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
